---
- name: Install Java 1.7
  apt: name=openjdk-7-jdk state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat
  sudo: yes

- name: delete home dir for symlink of tomcat
  shell: rm -fr /usr/share/tomcat
  sudo: yes

- name: Download Tomcat
  get_url: url=http://www.us.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin//apache-tomcat-7.0.61.tar.gz dest=/opt/apache-tomcat-7.0.61.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/ creates=/opt/apache-tomcat-7.0.61

- name: Symlink install directory
  file: src=/opt/apache-tomcat-7.0.61 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
# notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
# notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

#- name: chmod permissions of init.d/tomcat
#  shell: chmod 755 /etc/init.d/tomcat
#  sudo: yes


- name: Start Tomcat
  command: sudo /usr/share/tomcat/bin/startup.sh


- name: Ensure tomcat is running (and enable it at boot)
  command: service tomcat start
  #service: name=tomcat state=restarted enabled=yes

#- name: deploy iptables rules
#  template: src=iptables-save dest=/etc/sysconfig/iptables
#  notify: restart iptables

- name: wait for tomcat to start
  wait_for: port={{http_port}}
